INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (0, 'Server Owner', '服务器拥有者');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (1, 'Manage Server', '管理服务器');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (101, 'Manage Roles', '管理角色');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (102, 'Manage Permissions', '管理权限');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (103, 'Manage Emojis', '管理表情');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (2, 'View Channel', '浏览频道');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (3, 'Manage Channels', '管理频道');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (301, 'Create Channels', '创建频道');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (302, 'Edit Channels', '编辑频道');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (303, 'Delete Channels', '删除频道');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (4, 'Manage Channel Groups', '编辑频道组');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (401, 'Create Channel Groups', '创建频道组');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (402, 'Edit Channel Groups', '编辑频道组');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (403, 'Delete Channel Groups', '删除频道组');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (5, 'Send Messages', '发送消息');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (6, 'Revoke Messages(all)', '撤回消息(所有的)');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (601, 'Revoke Messages(self)', '撤回消息(自己发送的)');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (7, 'Manage Users', '管理用户');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (701, 'Invite Users', '邀请用户');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (702, 'Mute Users', '禁言用户');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (703, 'Kick Users(all)', '踢出用户(所有)');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (70301, 'Kick Users(server)', '踢出用户(服务器)');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (70302, 'Kick Users(voice channel)', '踢出用户(语音频道)');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (8, 'React Message', '添加回应');
INSERT INTO public.t_permissions (c_permission_id, c_description_en, c_description_cn) VALUES (114514, 'Test Permission', '测试权限');
