[postgres]
minconn = "1"
maxconn = "50"
#host = "www.dddqmmx.asia"
host = "127.0.0.1"
port = "5432"
database = "surf"
user = "postgres"
password = "114514"
[email_check]
email_host_user = ""
email_host_password = ""